import { z } from 'zod';

const HEX_64 = /^[0-9a-fA-F]{64}$/;

const schema = z.object({
  // Spec 0058: SLACK_*_TOKEN removed entirely from worker env config.
  // Slack credentials live in the DB connector_secrets table (managed via
  // dashboard install). The resolver at apps/worker/src/channels/slack/resolve-credentials.ts
  // queries the DB directly — no env path remains.
  GH_TOKEN: z.string().min(1),
  // Spec 0071: optional one-shot legacy import only. If set, the boot
  // sequence writes the value into backend_credentials once and the env is
  // ignored on subsequent boots. The runtime never reads it again — the
  // SDK call gets the token via per-call `env` opt + ~/.claude/.credentials.json.
  CLAUDE_CODE_OAUTH_TOKEN: z.string().min(1).optional(),
  // Spec 0071: 32-byte hex master key for envelope encryption of all DB
  // credentials (backend_credentials + connector_secrets). Generated by
  // `pnpm run docker:setup` if missing. Loss = unrecoverable credentials.
  ZENO_MASTER_KEY: z.string().regex(HEX_64, 'ZENO_MASTER_KEY must be 64 hex chars (32 bytes)'),
  LOG_LEVEL: z.enum(['trace', 'debug', 'info', 'warn', 'error']).default('info'),
  WORKSPACE_DIR: z.string().default('/workspace'),
  LOGS_RETENTION_DAYS: z.coerce.number().int().min(1).max(365).default(7),
});

export type Config = {
  github: { token: string };
  /**
   * Spec 0071: legacyOauthToken is the old `.env` value, used only for the
   * one-shot import to DB at boot. The runtime supplies the active token via
   * the materializer + per-call SDK env — never via `process.env`.
   */
  claude: { legacyOauthToken: string | null };
  masterKey: Buffer;
  logLevel: 'trace' | 'debug' | 'info' | 'warn' | 'error';
  workspaceDir: string;
  logsRetentionDays: number;
};

export function loadConfig(): Config {
  const parsed = schema.safeParse(process.env);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => `${issue.path.join('.')}: ${issue.message}`)
      .join('; ');
    throw new Error(`Invalid environment: ${issues}`);
  }
  const env = parsed.data;
  return {
    github: { token: env.GH_TOKEN },
    claude: { legacyOauthToken: env.CLAUDE_CODE_OAUTH_TOKEN ?? null },
    masterKey: Buffer.from(env.ZENO_MASTER_KEY, 'hex'),
    logLevel: env.LOG_LEVEL,
    workspaceDir: env.WORKSPACE_DIR,
    logsRetentionDays: env.LOGS_RETENTION_DAYS,
  };
}
